🐛 Fix errors when scanning container images (#1772)
This fixes two errors:
```
cnquery run container registry gcr.io/mondoo-base-infra/mvd:latest -c "asset{ name platform ids kind runtime title }" --verbose     
Error: accepts 1 arg(s), received 2
...
x accepts 1 arg(s), received 2
```

This check was introduced with
https://github.com/mondoohq/cnquery/pull/1503

And
```
cnquery run container registry gcr.io/mondoo-base-infra/mvd:latest -c "asset{ name platform ids kind runtime title }" --verbose 
DBG using provider os with connector container
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
DBG found valid container registry reference ref=gcr.io/mondoo-base-infra/mvd:latest
! unknown credentials for container image
[
  {
    "type": "ssh_agent"
  }
]
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x138f0a4]

goroutine 1 [running]:
go.mondoo.com/cnquery/providers/os/resources/discovery/container_registry.AuthOption({0xc00053f698?, 0x1, 0x1}, {0x0, 0x0})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/os/resources/discovery/container_registry/resolver.go:113 +0xc4
go.mondoo.com/cnquery/providers/os/resources/discovery/container_registry.(*Resolver).Resolve(0xc000312fc0?, {0x10a000007?, 0x7?}, 0x0?, 0xc0003101e0, {0x0, 0x0})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/os/resources/discovery/container_registry/resolver.go:54 +0x23a
go.mondoo.com/cnquery/providers/os/provider.(*Service).discover(0xc000610590?, 0xc0000fe900?)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/os/provider/provider.go:446 +0x65
```

The ssh agent was introduced with
https://github.com/mondoohq/cnquery/pull/1735

Signed-off-by: Christian Zunker <christian@mondoo.com>