Wire up the remainder of aws.iam.role.createdAt (#5216)
It was in the code but not the lr which caused failures

```
[failed] [].all()
  error: [aws] cannot set 'createdAt' in resource 'aws.iam.group', field not found
```

Signed-off-by: Tim Smith <tsmith84@gmail.com>